### ISSUE TITLE
Data prep issues?

### ISSUE THREAD

**Issue by yashkumaratri** [AcademiaSinicaNLPLab/sentiment_dataset#1]
We got a error

```
./preprocess.py -m corpus.yaml MR
Traceback (most recent call last):
  File "./preprocess.py", line 86, in <module>
    for line in f:
  File "/home/crisp/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 3841: invalid continuation byte
```

**Comment by yashkumaratri** [comment]
Oops ran on py3.6 , my bad
